# Generated by Django 5.2.6 on 2025-09-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Social', 'Social'), ('Workshop', 'Workshop'), ('Meetup', 'Meetup'), ('Conference', 'Conference'), ('Other', 'Other')], max_length=50)),
            ],
        ),
    ]
